[package]
name = "kunai-ebpf"
version = "0.1.0"
edition = "2021"
description = "Package containing eBPF code used by Kunai"
license = "../LICENSE"
repository = "https://github.com/kunai-project/kunai"
publish = false

[features]
# enable debug probes
debug = []

[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
kunai-common = { path = "../kunai-common" }
kunai-macros = { path = "../kunai-common/src/kunai-macros" }
paste = "1.0"

[[bin]]
name = "kunai-ebpf"
path = "src/main.rs"

[profile.dev]
opt-level = 3
# enable DI
debug = 2
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[profile.release]
opt-level = 3
# enable DI
debug = 2
debug-assertions = false
lto = true
panic = "abort"
codegen-units = 1

[workspace]
members = []
